### PR TITLE
Add Vue 3 framework integration on README

### PR DESCRIPTION
**Pull request by TotomInc**
Thanks for your awesome library!

I've been working quickly on a Vue 3 framework integration for Blaze Slider.

Actually, the package is published on npm in a beta state but will be very soon stable.

It's actually usable in a Vue 3 project. We can add/disable pagination and pass `BlazeConfig` as an `:options` prop.

### CODE REVIEW

**Comment by MananTank** [comment]
@TotomInc Thanks so much for the Vue Integration!
 
Can please create a sandbox and show this working in it?

Please also add a toggle button in the sandbox to mount and unmount (show and hide) the slider - I want to confirm that slider is only initialized once.

**Comment by wobsoriano** [comment]
I'd do it via composable/directive in Vue.

Composable

```ts
import type { BlazeConfig } from 'blaze-slider'
import type { Ref } from 'vue'
import BlazeSlider from 'blaze-slider'
import { unref, onMounted } from 'vue'

type MaybeRef<T> = Ref<T> | T

export function useBlazeSlider(el: MaybeRef<HTMLElement>, config?: BlazeConfig) {
  const slider = ref<BlazeSlider>(null)

  onMounted(() => {
    slider.value = new BlazeSlider(unref(el))
  })

  return slider
}
```

```html
<script setup lang="ts">
import { ref } from 'vue'
import { useBlazeSlider from '@/useBlazeSlider'
const el = ref<HTMLElement | null>(null)

const slider = useBlazeSlider(el)
</script>

<template>
  <div ref="el">
    <!-- other elements -->
  </div>
</template>
```

or via directive

```ts
import { createApp } from 'vue'
import BlazeSlider from 'blaze-slider'
import App from './App.vue'

const app = createApp(App)

app.directive('blaze-slider', (el, binding) => {
  new BlazeSlider(el, binding.value)
})

app.mount('#app')
```

```html
<template>
  <div v-blaze-slider="{...}">
    <!-- other elements -->
  </div>
</template>
```

**Comment by wobsoriano** [comment]
Another implementation via composable/directive

**Composable**

```ts
import type { BlazeConfig } from 'blaze-slider'
import type { Ref } from 'vue'
import BlazeSlider from 'blaze-slider'
import { unref, onMounted } from 'vue'

type MaybeRef<T> = Ref<T> | T

export function useBlazeSlider(el: MaybeRef<HTMLElement>, config?: BlazeConfig) {
  const slider = ref<BlazeSlider>(null)

  onMounted(() => {
    slider.value = new BlazeSlider(unref(el))
  })

  return slider
}
```

```html
<script setup lang="ts">
import { ref } from 'vue'
import { useBlazeSlider from '@/useBlazeSlider'
const el = ref<HTMLElement | null>(null)

const slider = useBlazeSlider(el)
</script>

<template>
  <div ref="el">
    <!-- other elements -->
  </div>
</template>
```

**Directive**

```ts
import { createApp } from 'vue'
import BlazeSlider from 'blaze-slider'
import App from './App.vue'

const app = createApp(App)

app.directive('blaze-slider', (el, binding) => {
  new BlazeSlider(el, binding.value)
})

app.mount('#app')
```

```html
<template>
  <div v-blaze-slider="{...}">
    <!-- other elements -->
  </div>
</template>
```

**Comment by TotomInc** [comment]
@MananTank are you talking about a CodeSandbox? Sure, I can create one showcasing the Vue integration with a toggle button to confirm the Slider is only mounted once.

@wobsoriano do you mind if I integrate your `useBlazeSlider` inside the vue-blaze-slider package? Or if you want, you can create a PR. 
The goal here is to provide both an abstracted way to create a slider (with components abstracting the DOM) and with a `use` hook for more control over the Slider DOM.

**Comment by MananTank** [comment]
@TotomInc Yes - Codesandbox please.

And Can you also remove the default Pagination and Navigation element structure or at least make the configurable so that they remain customisable ?

**Comment by TotomInc** [comment]
For anyone interested, the package is published at [`vue-blaze-slider`](https://www.npmjs.com/package/vue-blaze-slider).

**Pull request closed without merging**
