### PR TITLE
Feat: slideOnScroll functionality and config property

### LINKED ISSUE #14: [FEAT] Allow slide on scroll
Great project! Please add sliding on scrolling.

### PR DESCRIPTION
**Pull request by IRHM**
Created `slideOnScroll` property in config. When set to true, you can use the scroll wheel to navigate through slides. Defaults to false.

I put the actual functionality in `navigation.ts`, not sure if that's the best place, can move if there's a better place for it.

Closes #14

### CODE REVIEW

**Comment by IRHM** [comment]
I tested it and it seems to work properly, if you find any issues with it or if there's a better way you think it should work, let me know!

**Comment by IRHM** [comment]
@MananTank When you're available, could you give a look through this? Would be great if we could get it in the next release.

**Comment by MananTank** [comment]
Hi @IRHM Thanks for contributing! But I'm afraid there are lots of issues with this implementation: refer to below video: 

* Page scrolls down when scrolling over the slider vertically
* the page transitions are skipped sometimes

https://user-images.githubusercontent.com/22043396/198302349-9eaa754a-ff7e-4ca1-8432-a20a64aa0156.mov

Tested on Chrome, MacOS 13

**Comment by IRHM** [comment]
@MananTank My bad, didn't think about the scrolling on the page. Didn't notice the transition skipping sometimes, may be because of the scrolling down the page. I'm free in a few hours, may be able to try fixing that then.

Thanks for checking it out, appreciate it

**Comment by IRHM** [comment]
@MananTank The page scrolling should be fixed. I'm not sure about the transition skipping, I got it to happen once or twice but I had to try very hard to scroll as fast as I could, seems like this could be a non-issue? It may be more of an issue with the `next()`/`prev()` methods, not 100% sure.

**Comment by bhaveshxrawat** [comment]
@MananTank What's the status on this feat? Is it available to be used to?

**Pull request closed without merging**
